src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article {
    private $id;
    private $title;
    private $content;
    private $date;
    private $author_name;
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getAuthorName(): ?string
    {
        return $this->author_name;
    }

    public function setAuthorName(string $author_name): self
    {
        $this->author_name = $author_name;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Services\SwearCleaner;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BlogController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        // Récupération articles
        $article_repo = $this->getDoctrine()->getRepository(Article::class);

        // findAll() methode repository
        $articles = $article_repo->findAll();

        return $this->render('blog/index.html.twig', [
            'controller_name' => 'BlogController',
            'articles' => $articles
        ]);
    }

    /**
     * @Route("/article/{id}", name="article")
     */
    public function article(int $id): Response
    {
        $article_repo = $this->getDoctrine()->getRepository(Article::class);
        $article = $article_repo->find($id);

        $swear_cleaner = new SwearCleaner();
        $article = $swear_cleaner->cleanSwear($article);
        return $this->render('blog/article.html.twig', ['article' => $article]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Bienvenue sur mon premier blog Symfony{% endblock %}</title>
        <link rel="stylesheet" href="bootstrap.min.css">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="/">Blog Symfony</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Nouvel article</a>
                </li>
                </ul>
            </div>
        </nav>
        <div class="container">
            {% block body %}{% endblock %}
        </div>
        {% block javascripts %}{% endblock %}

    </body>
</html>

templates/blog/article.html.twig
{% extends "base.html.twig" %}

{% block body %}

<article class="jumbotron">
  <h1 class="display-3">{{ article.title }}</h1>
  <h2 class="display-3"></h2>
  <p class="lead">{{ article.authorName }}</p>
  <hr class="my-5">
  <p>{{ article.content }}</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="/" role="button">Retour</a>
  </p>
</article>

{% endblock %}

templates/blog/index.html.twig
{# herite du theme de base #}
{% extends 'base.html.twig' %}

{% block body %}

<div class="container row">
    {% for article in articles %}
        <section class="card text-dark bg-primary m-3 col-3" style="max-width: 20rem;">
            <div class="card-header">{{ article.title }}</div>
            <div class="card-body">
            <p>{{ article.category }}</p>
                <h4 class="card-title">{{ article.authorName }}</h4>
                <p class="card-text">{{ article.content }}</p>
            </div>
            <a href="{{ path('article',{'id':article.id}) }}" class="btn btn-success">Voir</a>
        </section>
    {% endfor %}
</div>

{% endblock %}